### ISSUE TITLE
Clicking on a first word of a comment crashes ghc-mod

### ISSUE THREAD

**Issue by petrroll** [hoovercj/vscode-ghc-mod#16]
When the first word of a comment is directly connected to the comment double-dash then hovering above it causes a ghc-mod crash. 
![issue_gh](https://cloud.githubusercontent.com/assets/1764721/15302204/093f3298-1bb2-11e6-9091-38cd3cacbe80.PNG)

**Comment by hoovercj** [comment]
Eventually I'll get this right.

A quick fix might be to set the log level for this extension to "none" in user or workspace. It won't prevent the crash but it might prevent the error bars.

I'll try to patch this tomorrow.

**Comment by hoovercj** [comment]
There's a patch that hopefully addresses this.

The issue is that vscode doesn't expose a "scopeAtPosition" api or anything to check if you're hovering in a comment or not. I'd really like to avoid reimplementing the textmate bundle into this to catch all these cases, so you might still find some strange comments or combinations that can cause errors, but hopefully I've caught the most common cases for now.
